
version: "3.2"

services:
    interface:
        build: .
        volumes:
            - type: bind
              source: ./database
              target: /database
        ports:
            - "80:80"
        depends_on:
            - "postgres"

    postgres:
        image: "postgres"
        environment:
            POSTGRES_PASSWORD: "password"