
version: "3"

services:
    interface:
        build: .
        ports:
            - "80:80"
        depends_on:
            - "postgres"

    postgres:
        image: "postgres"
        environment:
            POSTGRES_PASSWORD: "password"